### PR TITLE
chore:  add_dependencies is redundant

### PR DESCRIPTION
**Pull request by sandercox**
target_link_libraries already ensures target_dependencies. So manually maintaining these lists is redundant.

https://stackoverflow.com/questions/27282938/target-link-libraries-and-add-dependencies

### CODE REVIEW

**Comment by thomas43** [comment]
Hi, 

Thank you for submitting this Pull Request! I ran it on our end and all seems okay with 1 fix: The demo `ntv2cudalowlatency` did not seem to like calling `add_dependencies` with no parameters (`CUDA_OBJ`) is empty apparently. So I removed the line, similar to the rest of your changes.

If you are OK with this modification, I will merge it in. 

``` 
diff --git a/demos/NVIDIA/cudalowlatencydemo/CMakeLists.txt b/demos/NVIDIA/cudalowlatencydemo/CMakeLists.txt
index e38fece7..07742e40 100644
--- a/demos/NVIDIA/cudalowlatencydemo/CMakeLists.txt
+++ b/demos/NVIDIA/cudalowlatencydemo/CMakeLists.txt
@@ -97,7 +97,6 @@ elseif (CMAKE_SYSTEM_NAME STREQUAL "Darwin")
 elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(TARGET_LINK_LIBS X11 OpenGL::GL OpenGL::GLU GLEW::GLEW cuda dl pthread rt)
        add_executable(cudalowlatencydemo ${TARGET_SOURCES} kernel.cu)
-       add_dependencies(cudalowlatencydemo ${CUDA_OBJ})
        target_compile_definitions(cudalowlatencydemo PRIVATE ${TARGET_COMPILE_DEFS})
        target_include_directories(cudalowlatencydemo PRIVATE ${TARGET_INCLUDE_DIRS})
        target_link_libraries(cudalowlatencydemo PRIVATE ajantv2 ${TARGET_LINK_LIBS})
```

**Comment by sandercox** [comment]
I wasn't testing with CUDA nor on linux so happy to have that changed. But did you link against cuda otherwise I guess the CUDA_OBJ should be checked for contents before ignoring it or adding it to the list of dependencies.

**Comment by thomas43** [comment]
Yep I tested it in a build that links with the CUDA libs. I'll merge it in. Thanks again!

**Comment by thomas43** [comment]
Merged 50db3908

**Pull request closed without merging**
